CONTRIBUTING.md
REVIEW_CHECKLIST.md

Add CONTRIBUTING.md (which is a generalized version of previously reviewed and merged https://github.com/ansible-collections/community.mysql/pull/112)
Add REVIEW_CHECKLIST.md

Add CONTRIBUTING.md and REVIEW_CHECKLIST.md

---

review_checklist.rst

Add general tips to review_checklist

Add general tips to review_checklist

---

review_checklist.rst

Improve review_checklist.rst

---

contributing.rst

First mentioned here: https://github.com/ansible/community-docs/pull/6#discussion_r639631258
cc @Andersson007

Correct labels

---

maintaining.rst

maintaining.rst: fix a link

---

maintaining.rst

maintaining.rst: elaborate on importance of Contributor Summit

maintaining.rst: elaborate on importance of Contributor Summit

---

create_pr_quick_start_guide.rst
test_pr_quick_start_guide.rst

This has been initially brought up in https://github.com/ansible-collections/community.general/pull/2738, but after further discussion and as suggested by @Andersson007, this PR tries to include a more detailed documentation about how to test PRs locally.

Add Test PR Quick Start guide

---

contributing.rst

contributing.rst: add note about GH discussions
The paragraph has been copied from c.mysql and was originally made by @Jorge-Rodriguez, thank him!

contributing.rst: add note about GH discussions

---

maintaining.rst

maintaining.rst: change links to The Bullhorn

maintaining.rst: change links to The Bullhorn

---

maintaining.rst

maintaining.rst: add PR days info

maintaining.rst: improve

---

maintaining.rst

maintainers.rst: Add a stepping down section

maintainers.rst: Add a stepping down section

---

maintaining.rst

maintaining.rst: add team's email to the Stepping down section

maintaining.rst: add team's email to the Stepping down section

---

releasing_collections_with_release_branches.rst
releasing_collections_without_release_branches.rst

Update releasing guidelines

---

create_pr_quick_start_guide.rst
maintaining.rst
releasing_collections.rst
review_checklist.rst

Remove leading whitespaces

---

create_pr_quick_start_guide.rst

create_pr_quick_start_guide.rst: fix notes

create_pr_quick_start_guide.rst: fix notes

---

contributing.rst
contribution_to_project.rst

What is a contribution to an Open Source project. How it can be classified. It can help define the personas / stories for https://github.com/ansible-community/community-topics/issues/24.

Add contribution_to_project.rst

---

contributor_path.rst

Add the Contributor path. Any ideas are welcome.

Add contributor_path

---

maintaining.rst

maintaining.rst: fix ref formatting

maintaining.rst: fix formatting

---

create_pr_quick_start_guide.rst
review_checklist.rst

Improve create_pr_quick_start_guide and review_checklist

Improve create_pr_quick_start_guide and review_checklist

---

contribution_to_project.rst

Add a reference from contribution_to_project.rst to contributor_path.rst

Add a reference from contribution_to_project.rst to contributor_path.rst

---

integration_tests_quick_start_guide.rst

Add Quick-start integration testing guide

Add Quick-start integration testing guide

---

unit_tests_quick_start_guide.rst

Add unit testing quick-start guide.
https://docs.ansible.com/ansible/devel/dev_guide/testing_units_modules.html#why-use-unit-tests looks pretty decent but it would be nice to have something for beginners like this quick-start guide.

Unit testing guide

---

ansible_community_steering_committee.rst
steering_committee_guidelines.rst

Ansible Community Steering Committee Doc & Guidelines.

Ansible Community Steering Committee Doc & Guidelines

---

ansible_community_steering_committee.rst

Update Ansible Steering Committee doc

Update Ansible Steering Committee doc

---

ansible_community_steering_committee.rst
steering_committee_membership_guidelines.rst

Relates to https://github.com/ansible-community/community-topics/issues/72

Update Steering Committee guidelines
